# Generated by Django 4.0.9 on 2023-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog_title",
                    models.CharField(max_length=80, verbose_name="blog_title"),
                ),
                ("blog_content", models.TextField(verbose_name="blog_content")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="blog_created_at"
                    ),
                ),
            ],
        ),
    ]
